version: 2

sources:
  - name: velib
    database: velib
    description: "This source contains the raw data from the Velib system."
    schema: velib_raw
    tables:
      - name: station_status
      - name: station_information

  - name: meteo
    database: velib
    description: "This source contains the raw data from the Meteo system."
    schema: meteo_raw
    tables:
      - name: weather 